<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="MongoDB.Driver" Version="3.7.0" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.17.0" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="src\Application\Validators\" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="tests\PostmanCollection\Messaging\.resources\ChatHub.resources\messages\JoinChatRoom.message.yaml" />
	  <None Include="tests\PostmanCollection\Messaging\.resources\ChatHub.resources\messages\LeaveChatRoom.message.yaml" />
	  <None Include="tests\PostmanCollection\Messaging\.resources\ChatHub.resources\messages\Protocol.message.yaml" />
	  <None Include="tests\PostmanCollection\Messaging\.resources\ChatHub.resources\messages\SendMessageToChatRoom.message.yaml" />
	  <None Include="tests\PostmanCollection\Messaging\.resources\definition.yaml" />
	</ItemGroup>

</Project>